# Generated by Django 3.1 on 2021-03-31 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='paid_for',
            field=models.CharField(choices=[('RB', 'Room Bookings'), ('RT', 'Restuarant'), ('PT', 'Park Tickets')], default='RB', max_length=3),
        ),
    ]
