export const ADD_TO_BASKET = "ADD_TO_BASKET";
export const REMOVE_FROM_BASKET = "REMOVE_FROM_BASKET";
export const REMOVE_ALL_FOODS = "REMOVE_ALL_FOODS";
export const SAVE_ORDERS = "SAVE_ORDERS";
export const RETURN_COMPETED_ORDERS = "RETURN_COMPETED_ORDERS"
export const RETURN_CANCELED_ORDERS = "RETURN_CANCELED_ORDERS"
export const RETURN_PENDING_ORDERS = "RETURN_PENDING_ORDERS"