# Generated by Django 3.1 on 2021-03-12 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_on', models.DateField(auto_now_add=True)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('is_complete', models.BooleanField(default=False)),
                ('is_canceled', models.BooleanField(default=False)),
                ('by_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_booked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=256)),
                ('contact', models.CharField(max_length=16)),
                ('is_staying', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=32)),
                ('total_rooms', models.IntegerField()),
                ('tariff', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.IntegerField(unique=True)),
                ('active_booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.bookings')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='bookings.roomtype')),
            ],
        ),
        migrations.AddField(
            model_name='bookings',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booked', to='bookings.guests'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.rooms'),
        ),
    ]
