# Generated by Django 3.1 on 2021-03-22 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_on', models.DateTimeField(auto_now=True)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('num_of_rooms', models.IntegerField()),
                ('has_confirmed', models.BooleanField(default=False)),
                ('has_canceled', models.BooleanField(default=False)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_bookings', to='bookings.guests')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.roomtype')),
            ],
        ),
    ]
