# Generated by Django 3.1 on 2021-04-01 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_bookingrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='total_rooms',
        ),
        migrations.AddField(
            model_name='bookings',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookings',
            name='rate',
            field=models.FloatField(default=4000),
        ),
    ]
