# Generated by Django 3.1 on 2021-04-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_rooms_cottage_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='leaved_on',
            field=models.DateField(null=True),
        ),
    ]
