# Generated by Django 3.1 on 2021-05-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_bookings_leaved_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='applied_vat',
            field=models.FloatField(default=0.15),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='vat',
            field=models.FloatField(default=0.15),
        ),
    ]
