# Generated by Django 3.1 on 2021-05-29 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_auto_20210530_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='guests',
            name='arrived',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='guests',
            name='discount_bookings',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='guests',
            name='discount_food',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='guests',
            name='is_tenant',
            field=models.BooleanField(default=True),
        ),
    ]
