# Generated by Django 3.1 on 2021-05-30 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_auto_20210530_0527'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bookings',
            index=models.Index(fields=['-check_in', '-check_out'], name='bookings_bo_check_i_3e960f_idx'),
        ),
        migrations.AddIndex(
            model_name='bookings',
            index=models.Index(fields=['guest'], name='bookings_bo_guest_i_e3871d_idx'),
        ),
    ]
