# Generated by Django 3.1 on 2021-04-25 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_bookings_leaved_on'),
        ('tickets', '0002_auto_20210422_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='bought_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='bookings.guests'),
        ),
    ]
