# Generated by Django 3.1.7 on 2021-03-22 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300, null=True)),
                ('price', models.FloatField()),
                ('available', models.BooleanField(default=True)),
                ('food_type', models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lanch'), ('D', 'Dinner')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='FoodOrdering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('time', models.DateField(auto_now_add=True)),
                ('isComplete', models.BooleanField(default=False)),
                ('isCancel', models.BooleanField(default=False)),
                ('food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.fooditem')),
                ('guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.guests')),
                ('taken_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
