# Generated by Django 3.1.7 on 2021-03-22 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0001_initial'),
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodordering',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food', to='food.fooditem'),
        ),
        migrations.AlterField(
            model_name='foodordering',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guests', to='bookings.guests'),
        ),
        migrations.AlterField(
            model_name='foodordering',
            name='taken_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
