# Generated by Django 3.1.7 on 2021-03-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20210323_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodordering',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
