# Generated by Django 3.1.7 on 2021-03-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20210325_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='food_type',
            field=models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lanch'), ('S', 'Snacks'), ('D', 'Dinner')], max_length=1),
        ),
        migrations.AlterField(
            model_name='foodordering',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
