# Generated by Django 3.1.7 on 2021-04-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_foodordering_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='description',
            field=models.CharField(default='', max_length=300, null=True),
        ),
    ]
