# Generated by Django 3.1.7 on 2021-04-04 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_auto_20210402_0125'),
        ('food', '0006_foodordering_order_price'),
    ]

    operations = [
    ]
