# Generated by Django 3.1.7 on 2021-04-06 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_auto_20210406_1436'),
        ('food', '0007_merge_20210404_1318'),
    ]

    operations = [
    ]
