# Generated by Django 3.1.7 on 2021-04-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_auto_20210406_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodordering',
            name='custom_order',
            field=models.CharField(blank=True, default='', max_length=101, null=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='food_type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snacks', 'Snacks'), ('Pizza', 'Pizza'), ('Burger', 'Burger'), ('Chinese Platter', 'Chinese Platter')], max_length=15),
        ),
    ]
