# Generated by Django 3.1.7 on 2021-04-12 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_auto_20210408_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodordering',
            name='custom_order',
        ),
    ]
