# Generated by Django 3.1.7 on 2021-04-10 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_auto_20210408_2348'),
        ('food', '0008_merge_20210406_1618'),
    ]

    operations = [
    ]
