# Generated by Django 3.1.7 on 2021-04-13 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_merge_20210410_1150'),
        ('food', '0009_remove_foodordering_custom_order'),
    ]

    operations = [
    ]
