# Generated by Django 3.1.7 on 2021-05-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_auto_20210416_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodordering',
            name='notes',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
