# Generated by Django 3.1.7 on 2021-05-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_foodordering_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='vat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodordering',
            name='vat',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
