# Generated by Django 3.1.7 on 2021-05-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0013_auto_20210528_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='vat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='foodordering',
            name='notes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodordering',
            name='vat',
            field=models.FloatField(default=0.0),
        ),
    ]
